version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: symfony_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: prod